app/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name="index"),
    url('report.html/', views.report, name='report'),


]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^', include('app.urls')),
    url(r'^admin/', admin.site.urls),
]

app/forms.py
from django import forms

from .models import HospitalMRD, ClinicalPharmacist, AddNote


def available_stations():
    return HospitalMRD.objects.values_list("id", "MRD")


class SearchForm(forms.Form):
    MRD = forms.ChoiceField(
        label="MRD",
        choices=available_stations
    )
    date_from = forms.DateField(
        label="From",
        input_formats=['%Y-%m-%d',],
        widget=forms.TextInput(attrs={'size': 10}),
        required=False
    )
    date_to = forms.DateField(
        label="To",
        input_formats=['%Y-%m-%d',],
        widget=forms.TextInput(attrs={'size': 10}),
        required=False
    )

    def search(self):
        MRD = self.cleaned_data.get('MRD', None)
        date_from = self.cleaned_data.get('date_from', None)
        date_to = self.cleaned_data.get('date_to', None)

        data = ClinicalPharmacist.objects.filter()


        if MRD:
            data = data.filter(MRD=MRD)
        if date_from:
            data = data.filter(date__gte=date_from)
        if date_to:
            data = data.filter(date__lte=date_to)

        return data


class ReportForm(forms.Form):

    URINE_OUTPUT_CHOICES = [
    ('N', 'Normal'),
    ('O', 'Oliguria'),
    ('P', 'Polyuria'),
    ]

    BALANCE_CHOICES = [
    ('-V', '+Ve'),
    ('+V', '-Ve'),
    
    ]

    FEEDING_CHOICES = [
    ('NPO', 'NPO'),
    ('Oral', 'Oral'),
    ('NGT/OGT', 'NGT/OGT'),
    ('PEG', 'PEG'),
    ('TPN', 'TPN'),
    ]

   
    ELECTROLYTES_CHOICES = [
    ('Na', 'Na'),
    ('K', 'K'),
    ('Mg', 'Mg'),
    ('Po4', 'Po4'),
    ('Ca', 'Ca'),
    ]

    ABI_CHOICES = [
    ('Yes', 'Yes'),
    ('Normal', 'Normal'),
    ]



    HYPER_HYPO_CHOICES = [
    ('hyper', 'hyper'),
    ('hypo', 'hypo'),
    
    ]
    METABOLIC_CHOICES = [
    ('Acidosis', 'Acidosis'),
    ('Alkalosis', 'Alkalosis'),
    ]  

    RESPIRATORY_CHOICES = [
    ('Acidosis', 'Acidosis'),
    ('Alkalosis', 'Alkalosis'),
    ]            
          
    QT_C_CHOICES = [
    ('>500', '>500'),
    ('<500', '<500'),
    ]

    VITALS_CHOICES = [
    ('stable', 'stable'),
    ('tech carbon', 'techcarbon'),
    ('tachypnea'  , 'tachypnea'),
    ('htn', 'HTN'),
    ('bradycardia', 'bradycardia'),
    ('bradypnea', 'bradypnea'),
    ('hypotension', 'hypotension'),
    ('Fever', 'Fever'),
    ] 

    TP_CHOICES = [
    ('Normal', 'Normal'),
    ('Mechanical', 'Mechanical'),
    ('Pharmacology', 'Pharmacology'),

    ]

    SUP_CHOICES =[

            ('Normal','Normal'),
            ('Yes',(
                ('Pantoprazole-40-mg-IV-OD','Pantoprazole-40-mg-IV-OD'),
                ),
            ),

    ]

    
    T_BG_CHOICES = [
    
        ('G1',(
                ('Hypoglycomic', 'Hypoglycomic'),
                ('Glucagon', 'Glucagon'),
                ('D50%', 'D50%'),
                ('D5%/D10%', 'D5%/D10%')
                
                )
            ),
        ('G2',(
                ('koton', 'koton'),
                ('Hydration', 'Hydration'),
                )
            ),
        ('G3',(
                ('Hyperglycemia', 'Hyperglycemia'),
                ('Insulin Infusion', 'Insulin Infusion'),
                ('DKA protocol', 'DKA protocol'),
                ('SQ Sliding Scale', 'SQ Sliding Scale'),
                ('Long acting insulin', 'Long acting insulin'),

                
                
                
                )
            ),
    

    ]
    

    INFECTION_CHOICES = [
    ('UA', 'UA'),
    ('Markers', 'Markers'),
    ('Fever', 'Fever'),
    ('Culture', 'Culture'),
    ('X-Ray', 'X-Ray'),
    ('Swab', 'Swab'),


    ]   

    UA_CHOICES = [
    ('+Ve', '+Ve'),
    ('-Ve', '-Ve'),
    ] 



  

    TREATMENT_CHOICES = [
    ('Antifungal', 'Antifungal'),
    ('Antiviral', 'Antiviral'),
    ('Antimonial', 'Antimonial'),
    ('AB-A',(
                ('Ampicillin', 'Ampicillin'),
                ('Amoxiclav', 'Amoxiclav'),
                ('Amikacin', 'Amikacin'),
                ('Azithromycin','Azithromycin'),
                ('Anidulafungin','Anidulafungin'),
                ('Albendazole','Albendazole'),
                ('Acyclovir','Acyclovir'),
                
                )
    ),
    ('AB-C',(
                ('Cefazoline', 'Cefazoline'),
                ('Ceftriaxone', 'Ceftriaxone'),
                ('Cefotaxime','Cefotaxime'),
                ('Cefepim','Cefepim'),
                ('Ceftarolin','Ceftarolin'),
                ('Ceftazidim','Ceftazidim'),
                ('Ceftazidim/avibactam','Ceftazidim/avibactam'),
                ('Cftobiprole','Cftobiprole'),
                )
            ),
    ('AB-E',(
                ('Ertapenem', 'Ertapenem'),
                ('Tigecycline', 'Tigecycline'),
                
                
                
                )
            ),

             
    ('AB-F',(
                ('Flucloxacillin ', 'Flucloxacillin'),
                ('Fluconazole', 'Fluconazole'),
                
                
                )
            ),
    ('AB-G',(
                ('Gentamycin', 'Gentamycin'),
                ('Ganciclovir', 'Ganciclovir'),
                
                
                
                )
            ),
    ('AB-P',(
                ('Penicillin G', 'Penicillin G'),
                ('Piperacillin/tazobactam', 'Piperacillin/tazobactam'),
                ('Pentamidine', 'Pentamidine'),
                
                
                )
            ),

    ('AB-V',(
                ('Vancomycin', 'Vancomycin'),
                ('Voriconazole', 'Voriconazole'),
                
                
                
                )
            ),
    ('AB-T',(
                ('Teicoplanin', 'Teicoplanin'),
                ('Tigecycline', 'Tigecycline'),
                
                
                
                )
            ),
    ('AB-M',(
                ('Meropenem', 'Meropenem'),
                ('Metronidazole', 'Metronidazole'),
                
                
                
                )
            ),
    ('AB-I',(
                ('Imipenem cilastatin', 'Imipenem cilastatin'),
                ('Isavuconazole', 'Isavuconazole'),
                
                
                
                )
            ),
             
    ('AB-L',(
                ('Levofloxacin', 'Levofloxacin'),
                ('Linezolid', 'Linezolid'),
                
                
                
                )
            ),
              
    ('AB-V',(
                ('Voriconazole', 'Voriconazole'),
                ('Ganciclovir', 'Ganciclovir'),
                
                
                
                )
            ),
    ('AB-R',(
                ('Remdesivir', 'Remdesivir'),
                
                
                
                
                )
            ),
   
]
    AB_INTERVENTION_CHOICES = [

            ('Intervention',(
                ('Escalution-need','Escalution'),
                ('De-escalution-need','De-escalution'),
                ('Renal-dose-adjustment','Renal-dose-adjustment'),
                ('hepatic-dose-adjustment','hepatic-dose-adjustment'),
                ('Renal-dose-adjustment','Renal-dose-adjustment'),
                ('Discontinue','Discontinue'),
                )
            ),
    ]

    AB_MP_CHOICES = [

        
            ('Monitoring Parameter',(
                ('Markers','Markers' ),
                ('Platelets','Platelets' ),
                ('QT-c','QT-c' ),
                ('Level','Level' ),
                ('Interaction','Interaction' ),
                ('Candida_Score','Candida_Score' ),
                ('Lactate','Lactate' ),
                ),
            ),

       ]

    

    MRD = forms.ChoiceField(label="MRD",choices=available_stations)    
    date = forms.DateField()
    GFR = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder':'GFR'}))
    Child_pugh_score = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder':'CPS'}))
    Liver_Imparrenenty = forms.BooleanField(required=False)
    Dose_adjustment = forms.BooleanField(required=False)
    Urine_output = forms.ChoiceField(choices=URINE_OUTPUT_CHOICES)
    Balance = forms.ChoiceField(choices=BALANCE_CHOICES)
    intervention =forms.CharField(required=False)
    Feeding = forms.ChoiceField(choices=FEEDING_CHOICES)
    Bowel_motion = forms.CharField(required=False)    
    Electrolytes_imbalance = forms.ChoiceField(choices=ELECTROLYTES_CHOICES)    
    Hyper_Hypo = forms.ChoiceField(choices=HYPER_HYPO_CHOICES)
    ABI = forms.ChoiceField(choices=ABI_CHOICES) 
    Metabolic_num = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder':'Metabolic'}))
    Respiratory_num = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder':'Respiratory'}))
    Metabolic = forms.ChoiceField(choices=METABOLIC_CHOICES)
    Respiratory = forms.ChoiceField(choices=RESPIRATORY_CHOICES)
    QT_C_num  = forms.IntegerField(widget=forms.TextInput(attrs={'placeholder':'Respiratory'}))
    QT_C= forms.ChoiceField(choices=QT_C_CHOICES)
    VITALS= forms.ChoiceField(choices=VITALS_CHOICES)
    Analgesic_management  = forms.BooleanField(required=False)
    Sedation = forms.BooleanField(required=False)
    Thromboembolic_Prophylaxis = forms.ChoiceField(choices=TP_CHOICES)
    Stress_Ulcer_Pophylaxis = forms.ChoiceField(choices=SUP_CHOICES )
    Glycemic_control_target_BG  = forms.BooleanField(required=False)
    T_BG = forms.ChoiceField(  choices=T_BG_CHOICES )
    Infection  = forms.ChoiceField(  choices=INFECTION_CHOICES )
    Treatment  = forms.ChoiceField(  choices=TREATMENT_CHOICES )

app/templates/app/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>HP-REPORT</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- borrow admin style -->
  <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css"/>
  <link rel="stylesheet" type="text/css" href="/static/admin/css/widgets.css"/>
  <link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css"/>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <!-- override some style -->

  <style>
    html {
      overflow: hidden;
      height: 100%;
      background: #5f3f3f;
    }
    body {
      overflow: auto;
      max-height: 100%; max-width: 800px;
      margin: 0 auto; /* center */ padding: 0 20px;
      border: 1px solid black; border-width: 0 1px;
      background: #2b2b2b;
      font-size: 14px;
      font-family: "Roboto","Lucida Grande","DejaVu Sans","Bitstream Vera Sans",Verdana,Arial,sans-serif;
    }
    header, nav, aside, article, footer, main, ol, li {
      display: flex;
    }
    nav, footer, {
      flex-direction: row;
      flex-wrap: nowrap;
    }
    header, main, article, aside {
      flex-direction: column;
    }
    header a { text-decoration: none; color: #3458B0; }
    nav a:hover { text-decoration: underline; }
    header h1 {
        font-size: 24px;
        margin-top: 12px;
        margin-bottom: 0px;
        text-align: center;
    }
    header h2 {
        font-size: 16px;
        margin-top: 6px;
        margin-bottom: 20px;
        text-align: center;
        color: #969696;
    }
    nav { border-bottom: solid 1px black; border-top: solid 1px black;}
    nav ol { padding-left: 0; margin: 8px 8px 8px 0; }
    nav ol li a { padding-right: 12px; }
    aside { float: right; padding: 0; border-left: dashed 1px black; border-bottom: dashed 1px black; max-width: 220px; }
    aside h1 { font-size: 24px; margin: 24px 0 0 0; padding-left: 12px; }
    aside p { margin: 12px; }
    main { align-items: center; padding: 24px; }
    main table caption h1 { font-size: 24px; margin: 12px 0 8px 0; text-align: left; }
    main table thead tr th { text-align: right; padding-right: 40px;}
    main table tbody tr td { text-align: right; font-size: 14px; padding-right: 40px; }
    footer { width: 100%; border-top: solid 1px black; justify-content: center; }
    div#search_form { display: flex; width: 100%; justify-content: space-around;}
    div#search_form div label { display: inline; }
    div#search_form div input { display: block; }
    div#search_form div select { display: block }
    div#search_form div button  { margin-top: 24px; }
  </style>
</head>

<body>
  <header>
      <h1><a href="/">Hopital Report </a></h1>

      

      <nav>
          <ol>
              <li><a href="{% url 'admin:index' %}">Demo admin</a></li>
             <!-- <li><a href="http://xlsxwriter.readthedocs.io/">XlsxWriter</a></li>
              <li><a href="http://www.reportlab.com/documentation/">ReportLab docs</a></li> -->
              <li><a href="{% url 'report' %}">Report</a></li>


          </ol>
      </nav>
  </header>

  

  <form method="post">
  {% csrf_token %}
  <main>
    <div id="search_form">
        {% for field in form %}
            <div>
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
        {% endfor %}
        <div class="buttons">
            <button class="small" type="submit">Filter</button>
        </div>
    </div>
    <table>
      <caption>
      </caption>
      <thead>
        <tr>
          <th>Date</th>
          <th>MRD</th>
          <th>Patient Name</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {% for row in data %}
        <tr>
            <td>{{ row.date|date:"Y-m-d" }}</td>
            <td>{{ row.MRD }}</td>
            <td>{{ row.patient }}</td>
            <td>{{ row.status }}</td>
        {% endfor %}
      </tbody>
    </table>
    <p>
        <button name="excel">Excel</button>
        <button name="pdf">PDF</button>
    </p>
  </main>
  </form>

  <footer>
  </footer>

  <script>  
    var django = django || {};
    django.jQuery = $;
  </script>  
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
    $( function() {
        $("#id_date_from").datepicker({ dateFormat: "yy-mm-dd" });
        $("#id_date_to").datepicker({ dateFormat: "yy-mm-dd" });
    });
  </script>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>

</body>
</html>

app/templates/app/index2.html

  <html>
    <head>
      <!--Import Google Icon Font-->
      <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <!--Import materialize.css-->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css"/>
      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head>

    <body>
      <div class="teal lighten-4">
      <div class= "container z-depth-3 white">
        
      <nav>
        <div class="nav-wrapper z-depth-3 ">
          <a href="" class="brand-logo center">Logo</a>
          <ul id="nav-mobile" class="left hide-on-med-and-down">
            <li><a href="#">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>
          </ul>
        </div>
      </nav>
        
        <br></br> 
          <p class="center">enter catchy phrase here for portfolio</p>   
        <br></br>

      <div class="center">
      <img src="http://lorempixel.com/320/320/abstract/1" alt="company logo" class="responsive-img circle hoverable ">
      </div>
    
      <br></br>
    
<div class="row center">
  <div class="col l4, col s4">Blah
  </div>
  <div class="col l4 col s4">Blah
  </div>
  <div class="col l4 col s4">Blah
  </div>
</div>
    
    <br></br>
    
      </div> 
      <!-- end of container -->
</div>
      
      
      
      
      
      
      
      
      
      
      
      <!--Import jQuery before materialize.js-->
      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
   
      
      
      
    </body>
  </html>
        